name: py-rocket

channels:
  - conda-forge
  - nodefaults

# The base packages for a JupyterHub with bells and whistles
dependencies:
  - python~=3.11.0
  # Required until https://github.com/jupyterhub/repo2docker/pull/1196 is merged
  - jupyterhub-singleuser~=4.0.1
